const images = {
    logo: require('../assets/img/logo.png'),
    profile: require('../assets/img/profile.png'),
    backgroundHeader: require('../assets/img/background.png'),
    backgroundFranchise: require('../assets/img/background2.png'),
    gallery1: require('../assets/img/gallery1.png'),
    gallery2: require('../assets/img/gallery2.png'),
    gallery3: require('../assets/img/gallery3.png'),
    gallery4: require('../assets/img/gallery4.png'),
    gallery5: require('../assets/img/gallery5.png'),
    gallery6: require('../assets/img/gallery6.png'),
    gallery7: require('../assets/img/gallery7.png'),
    gallery8: require('../assets/img/gallery8.png'),
    menu1: require('../assets/img/menu1.png'),
    menu2: require('../assets/img/menu2.png'),
    menu3: require('../assets/img/menu3.png'),
    menu4: require('../assets/img/menu4.png'),
    menu5: require('../assets/img/menu5.png'),
    menu6: require('../assets/img/menu6.png'),
    poster: require('../assets/img/poster.png'),
    benefit: require('../assets/img/benefit.png'),
    benefitMini: require('../assets/img/benefitMini.png'),
    modal: require('../assets/img/modal.png'),
    modalMini: require('../assets/img/modalMini.png'),
    price: require('../assets/img/price.png'),
    priceMini: require('../assets/img/priceMini.png'),
    stepByStep: require('../assets/img/stepByStep.png'),
    stepByStepMini: require('../assets/img/stepByStepMini.png'),
    trusted: require('../assets/img/trusted.png'),
    realiable: require('../assets/img/realiable.png'),
    profit: require('../assets/img/profit.png'),
    posterFranchise: require('../assets/img/posterFranchise.png'),
    sponsor1: require('../assets/img/sponsor1.png'),
    sponsor2: require('../assets/img/sponsor2.png'),
    sponsor3: require('../assets/img/sponsor3.png'),
    sponsor4: require('../assets/img/sponsor4.png'),
    sponsor5: require('../assets/img/sponsor5.png'),
    contact: require('../assets/img/contact.png'),
    map: require('../assets/img/map.png'),
    email: require('../assets/img/email.png'),
    whatsapp: require('../assets/img/whatsapp.png'),
    send: require('../assets/img/send.png'),
    facebook: require('../assets/img/facebook.png'),
    instagram: require('../assets/img/instagram.png'),
    twitter: require('../assets/img/twitter.png'),
    floatButton: require('../assets/img/floatButton.png')

}

export default images